#spring:
#  profiles:
#    active: dev

# 日志配置
logging:
  pattern:
    console: "%d - %msg%n"
#  level:
#    com.bennyrhys.wechat_order.LoggerTest: debug

#  level: debug # 直接指定级别
#  path: /Users/bennyrhys/Documents/Idea_Demo/WeChat-Order/wechat_order/src/main/resources/ # 弃用了
#  file: /Users/bennyrhys/Documents/Idea_Demo/WeChat-Order/wechat_order/src/main/resources/sell.log # 弃用了

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.210.134/db_wxds?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

    # 配置json为nll的字段 不显示

# 配置项目前缀
server:
  servlet:
    context-path: /sell


# 配置微信公众号
wechat:
#  用户授权-测试号
  mpAppId: wxc10086806f4c0df0
  mpAppSecret: bdcb164ea61b4b1cc6846cd549325898

#  支付号-不用secret
#  mpAppId: wxd898fcb01713c658
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/wechat-cert/h5.p12
  notifyUrl: http/sell/pay/notify # 最好用外网地址【微信异步通知】
